name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          cd backend
          pytest -v
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          DATABASE_URL: ":memory:" # Use in-memory SQLite database for tests

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Verify package.json and package-lock.json
        run: |
          cd frontend/ai-methods-explorer
          npm install --package-lock-only
      - name: Install dependencies
        run: |
          cd frontend/ai-methods-explorer
          npm ci
      - name: Build
        run: |
          cd frontend/ai-methods-explorer
          npm run build
